require("config.plugins")
require("config.lsp")
require("config.cmp")
require("config.treesitter")
require("config.terminal")
require("config.keybindings")
require("config.colorscheme")
require("config.settings")
